### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [elraccoone/unity-tweens#13]
Git tag: 1.6.2
package.json version: 1.6.1 https://github.com/elraccoone/unity-tweens/blob/1.6.2/package.json

To fix:
- Opt1: bump version then re-tag 1.6.2
- Opt2: bump version to 1.6.3, then create new Git tag 1.6.3

Refs, https://openupm.com/packages/nl.elraccoone.tweens/?subPage=pipelines

**Comment by jeffreylanters** [comment]
Hi, thanks for reminding me. I see I pushed after creating the tag, I'll fix it right away.
